#!/bin/zsh

# Build
make clean
make

# Activity 1
./build/test-glfip-1 images/mandrill.png renderings/activity1.png
./build/test-glfip-1 -z images/mandrill.png renderings/activity1-z.png

# # Activity 2
# ./build/test-glfip-2 images/mandrill.png renderings/activity2.png
# ./build/test-glfip-2 -c images/mandrill.png renderings/activity2-c.png

# # Activity 3
# ./build/test-glfip-3 images/mandrill.png activite-3-resultat.png activite-3-as.png activite-3-ps.png

# # Activity 4
# ./build/test-glfip-4 images/mandrill.png activite-4_0-30-0.png 0 30 0
# ./build/test-glfip-4 images/mandrill.png activite-4_0-30-1.png 0 30 1
# ./build/test-glfip-4 images/mandrill.png activite-4_0-5-0.png 0 5 0 
# ./build/test-glfip-4 images/mandrill.png activite-4_30-80-1.png 30 80 1

# # Activity 5
# ./build/test-rgbfip-4 images/napoli.png activite-5_0-5-0.png 0 5 0 
# ./build/test-rgbfip-4 images/napoli.png activite-5_1-20-1.png 1 20 1
# ./build/test-rgbfip-4 images/napoli.png activite-5_20-100-1.png 20 100 1
